### ISSUE TITLE
Font Awesome Take Down Request

### ISSUE THREAD

**Issue by alexpoiry** [OpenInternet/Infuse#3]
Hello,

I am the head of security for Font Awesome. This repository contains a complete collection of all our Font Awesome Pro assets (https://github.com/OpenInternet/Infuse/tree/main/assets/icons). These cannot be made available for free via a public repository. I would like to politely request that you remove these items from your repo and all branches.

I assume you didn't intend to violate our license and so would like to work with you and give you the time and opportunity to correct these issues before filing a DMCA request with GitHub. Please respond to this issue and provide a point of contact so that we can work to remedy this issue.

**Comment by AnXh3L0** [comment]
Hi @alexpoiry, thanks for opening this issue. I have contacted you via email to discuss this matter. 
Thanks, Anxhelo!

**Comment by AnXh3L0** [comment]
The Pro assets have been removed, now publishing only Free ones.
