### ISSUE TITLE
Links on resources at Spanish module1 from learning paths 6

### ISSUE THREAD

**Issue by deimidis** [OpenInternet/Infuse#60]
Hi, there are some links not working in the resources section. I think the problem is that the code for url includes the name:

`url="Qurium: https://www.qurium.org/secure-hosting/"`

I can make the changes and create a pull request, but I couldn't test it locally so I'm not sure that is the problem (right now, the link goes to infuse site)

**Comment by lukasz-a-krol** [comment]
Thanks so much for letting us know about this! :) We found some other links that have this issue and should have managed to fix them all by now
